---
- hosts: vms-do
  vars_prompt:
    - name: ovpn_pki_password
      prompt: "Enter OpenVPN RSA passphrase"
    - name: ovpn_pem_password
      prompt: "Enter OpenVPN PEM file passphrase"
    - name: ovpn_client_name
      prompt: "Enter OpenVPN new client name"

  remote_user: root

  tasks:

  - name: Generate OpenVPN PEM
    expect:
      command: docker run -v ovpn_vol:/etc/openvpn --log-driver=none --rm -it kylemanna/openvpn easyrsa build-client-full {{ ovpn_client_name }}
      timeout: 600
      responses:
        Enter PEM pass phrase: "{{ ovpn_pem_password }}"
        Verifying - Enter PEM pass phrase: "{{ ovpn_pem_password }}"
        Enter pass phrase for(.*): "{{ ovpn_pki_password }}"

  - name: Create OpenVPN PEM file
    shell: |
      docker run -v ovpn_vol:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_getclient {{ ovpn_client_name }} > {{ ovpn_client_name }}.ovpn
    args:
      chdir: /tmp
      creates: /tmp/{{ ovpn_client_name }}.ovpn

  - name: Fetch OpenFPN PEM file from remote
    fetch:
      flat: yes
      src: /tmp/{{ ovpn_client_name }}.ovpn
      dest: ./

  - name: Remove PEM file
    file:
      state: absent
      path: /tmp/{{ ovpn_client_name }}.ovpn